### ISSUE TITLE
The server timeout should be configurable

### ISSUE THREAD

**Issue by pvalsecc** [camptocamp/docker-haproxy-rancher#1]
30s is not enough for some APIs.

https://github.com/camptocamp/docker-haproxy-rancher/blob/defa8987e4091a0fdd9de1dfd142277f9442ad54/haproxy.d/01-defaults.cfg#L7

**Comment by Vampouille** [comment]
@pvalsecc You can configure it with rancher-compose.yml :

```yml
version: '2'
services:
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      config: |-
        defaults
            timeout client 1200000
            timeout server 1200000
```
